---
title: "Untitled"
author: ""
date: ""
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
###load packages 
library(readr)
library(mice)
require(mosaic)
library(car)
library(ggplot2)
library(ggvis)
# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```
 
```{r,eval=FALSE}
### reading the data and renaming the variables
data1 <- read.table("http://pmatheson.people.amherst.edu/Pima.dat", sep=",")
data1 <- rename(data1, "PREG" = V1, "PLASMA"=V2,"BP"= V3,"THICK"=V4,"INSULIN"=V5,"BODY"=V6,"PEDIGREE"=V7,"AGE"=V8,"RESPONSE"=V9) 

###creating new colums INSULIN22 and THICK22 to replace the 0's to the median 
data1["INSULIN22"] <- ifelse(data1$INSULIN!=0, data1$INSULIN, 125)
data1["THICK22"] <- ifelse(data1$THICK!=0, data1$THICK, 29)

###changing the 0's to NA's 
data1["INSULIN"] <- ifelse(data1$INSULIN==0, data1$INSULIN==NA,data1$INSULIN)
data1["BODY"] <- ifelse(data1$BODY==0, data1$BODY==NA, data1$BODY) 
data1["BP"] <- ifelse(data1$BP==0, data1$BP==NA, data1$BP)
data1["THICK"] <- ifelse(data1$THICK==0, data1$THICK==NA, data1$THICK)
data1["PLASMA"] <- ifelse(data1$PLASMA==0, data1$PLASMA==NA, data1$PLASMA)
View(data1)

 
###checking for multicollinearity  
model12 <- glm(RESPONSE ~ AGE+PREG+PLASMA+BP+THICK+ INSULIN+BODY+PEDIGREE,is.na,family=binomial, data=data1 )

vif(model12)  # 
 
 
###to find which variables are missing in the same row
md.pattern (data1) 

###logistic models 
fullmodel <- glm(RESPONSE ~ AGE+ PREG+is.na(PLASMA)+is.na(BP)+THICK22+ INSULIN22+is.na(BODY)+ PEDIGREE ,family=binomial, data=data1)
step(fullmodel,direction = "both" ) ### applying stepwise regression 
###our final model
modelfinal <- glm(formula = RESPONSE ~ AGE + PREG + is.na(BP) + THICK22 + INSULIN22 + PEDIGREE, family = binomial, data = data1)
summary(modelfinal)
```

```{r}
###filtering who has diabetes and who does not 
datanodi <- filter(data1, RESPONSE==0)
datayesdi <- filter(data1, RESPONSE==1)
###to find the mean of each variables 
favstats(datanodi$BODY)$mean
favstats(datayesdi$BODY)$mean 
```

 

```{r}
# just manualing tallying the variables 
tally(~data1$THICK) #227
tally(~data1$PREG)#111 but understandable 
tally(~data1$PLASMA) #5
tally(~data1$BP) #35
tally(~data1$INSULIN) #374
tally(~data1$BODY) #11
tally(~data1$PEDIGREE) #0
tally(~data1$AGE)
tally(~data1$RESPONSE) #response 
```


 

 
 



